name: Actions Workflow 

on: [push]

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    env:
      TEST_TENANT_INFO: ${{ secrets.TEST_TENANT_INFO }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: List files
        run: |
          pwd
          ls
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Crutch 
      - name: Log Greet time
        run: echo "${{ steps.greet.outputs.time}}"
      - name: Tell Secrets
        run: |
          echo $env:TEST_TENANT_INFO
