name: Actions Workflow 

on: [push]

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hellow-world-javascript-action@v1
        with: 
          who-to-greet: Crutch 
      - name: Log Greet time
        run: echo "{{ steps.greet.outputs.time}}"