name: Run Azure Login with OpenID Connect and PowerShell
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      environment: CodeSigning
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

        - name: 'Get resource group with PowerShell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               dotnet --version
               dotnet tool install --global AzureSignTool --version 4.0.1 
               Get-AzResourceGroup
               $Token = Get-AzAccessToken -ResourceTypeName KeyVault
               AzureSignTool sign -coe -fd sha256 -kvu https://githubautomationvault.vault.azure.net/ -kvc ScubaCodeSigning-Dev -ifl SignList.lst -kvm
             azPSVersion: "latest"
